.dashExtensions_js_metadata <- function() {
deps_metadata <- list(`dash_extensions` = structure(list(name = "dash_extensions",
version = "0.1.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-lottie.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashExtensions",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_extensions` = structure(list(name = "dash_extensions",
version = "0.1.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-mermaid.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashExtensions",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_extensions` = structure(list(name = "dash_extensions",
version = "0.1.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-lottie.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashExtensions",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_extensions` = structure(list(name = "dash_extensions",
version = "0.1.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-mermaid.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashExtensions",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_extensions` = structure(list(name = "dash_extensions",
version = "0.1.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_extensions.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashExtensions",
all_files = FALSE), class = "html_dependency"),
`dash_extensions` = structure(list(name = "dash_extensions",
version = "0.1.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_extensions.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashExtensions",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
